### ISSUE TITLE
how to run those gox files?

### ISSUE THREAD

**Issue by abbychau** [goplus/yap#69]
is it related to https://github.com/goplus/gox ?

but i cannot find any usage of it. could you help?

**Comment by xushiwei** [comment]
install [gop v1.2.0](https://github.com/goplus/gop?tab=readme-ov-file#how-to-install) and then:

```sh
cd <DirWhereGoxFileExists>
gop run .
```

**Comment by xushiwei** [comment]
Add basic introduction about yap: https://github.com/goplus/gop#go-classfiles

**Comment by abbychau** [comment]
what about in cli? how to generate go files using gop for gox files?

**Comment by xushiwei** [comment]
> what about in cli? how to generate go files using gop for gox files?

```
gop go .
```
